### ISSUE TITLE
Setup SSL

### ISSUE THREAD

**Issue by ericlathrop** [louisvilletech/louisvilletech.org#1]
The site should be served from SSL.

**Comment by ericlathrop** [comment]
https://docs.ansible.com/ansible/latest/letsencrypt_module.html

**Comment by ericlathrop** [comment]
I've figured out how to setup Let's Encrypt for one of my other sites. I still need to figure out the nginx http->https redirect part, then I can impement https here.

**Comment by ericlathrop** [comment]
According to @strongjz I just need to add:
```
  if ($scheme = http) {
       return 301 https://$server_name$request_uri;
```
to the server block.

**Comment by ericlathrop** [comment]
Some good pointers here: https://www.linuxbabe.com/ubuntu/nginx-lets-encrypt-ubuntu-16-04-17-10

**Comment by ericlathrop** [comment]
SSL is enabled! Getting an A+ on the SSL Labs test!
![screenshot from 2017-12-19 23-50-54](https://user-images.githubusercontent.com/530891/34191766-9f5072da-e517-11e7-8533-5d836051bdfc.png)

**Comment by rnhurt** [comment]
One final task: update the link on the Github page to be httpS://louisvilletech.org/ instead of http://louisvilletech.org/  :)

**Comment by ericlathrop** [comment]
@rnhurt done!
